alias ls='ls --color=auto'
alias c='clear'
alias d='cd "$(ls -d */ | fzf)"; clear; exa --all --long --header --sort=modified'
alias datedir='mkdir "$(date +%Y%m%d)"'
alias kooha='GST_VAAPI_ALL_DRIVERS=1 KOOHA_VAAPI=1 kooha'
alias battery1='mconnectctl show-battery /org/mconnect/device/1'
alias battery='mconnectctl show-battery /org/mconnect/device/4'
alias grep='grep --color=auto'
alias mcon='/usr/local/bin/mconnect -d'
alias ll='exa --all --long --header --sort=modified'
alias cll='clear && exa --all --long --header --sort=modified'
alias cls='clear; ls --color=auto'
alias cdcl='cd ; clear'
alias cfetch='clear ; neofetch'
alias lld='ls -d */'
alias llb='exa --all --long --header --sort=modified | bat'
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias gd='git diff'
alias ga='git add'
alias httptossh='git remote set-url origin'
alias rm='sh $HOME/git/scripts/mvtrash'
alias cp='cp -iv'
alias mv='mv -iv'
alias synctoserver='rsync -ruvP $HOME/git/andrewstephen.xyz/ root@andrewstephen.xyz:/var/www/andrewstephen'
#alias yay='paru'
alias technoblade='doas pacman -Rs $(pacman -Qtdq)'
alias scr='sxiv ~/Screenshots'
alias wall='sxiv ~/wallpapers'
alias phone='cd /run/user/1000/a2f66128170a1390/'
alias path='pwd | zenity --text-info --width=300 --height=130'
alias clock='tty-clock -c'
alias update='doas pacman -Syu'
alias sxiv='sxiv -a'
alias sleep='xset dpms force off'
alias rtpset0='pactl load-module module-rtp-send source=rtp.monitor port=1234 destination_ip=192.168.0.171'
alias rtpset1='pactl load-module module-rtp-send source=rtp.monitor port=1234 destination_ip=192.168.0.60'
#alias speed='speedtest-cli --simple --secure --bytes | sed 's/byte/B/''
alias droidfix='systemctl restart waydroid-container'
alias cmatrix='cmatrix -a'
alias librewolf='HOME=$HOME/.config librewolf'
alias newsboat='HOME=$HOME/.config newsboat --quiet'
#alias scrcpy='adb connect 192.168.0.178 && scrcpy'
alias mem='free -h'
#alias mpv='mpv --force-seekable=yes'
alias mpa='mpv --vo=null'
#alias mp1440='mpv --force-seekable=yes --ytdl-format="bestvideo[ext=mp4][height<=?1440]+bestaudio[ext=m4a]"'
#alias mp1080='mpv --ytdl-format="bestvideo[ext=mp4][height<=?1080]+bestaudio[ext=m4a]"'
#alias mp720='mpv --force-seekable=yes --ytdl-format="bestvideo[ext=mp4][height<=?720]+bestaudio[ext=m4a]"'
#alias mp480='mpv --force-seekable=yes --ytdl-format="bestvideo[ext=mp4][height<=?480]+bestaudio[ext=m4a]"'
alias mpvtty='mpv --force-seekable=yes --no-audio-display'
export wmname="$(wmctrl -m | head -n1 | cut -d' ' -f2)"
[[ wmname == 'dwm' ]] && alias mpv='dwmswallow $WINDOWID -c mpv; mpv'
alias temp='inxi -s'
alias tmpvar='XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland'
alias poweroff='loginctl poweroff'
alias reboot='loginctl reboot'
alias logout='pkill "$USER_WM"'
